webtest/webtest/webtest/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using webtest.Models;

namespace webtest.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Authorize(User userModel)
        {
            using (DatabaseEntities1 db = new DatabaseEntities1())
            {
                var userPassword = Crypto.Hash(userModel.Password);
                var userData = db.Users.Where(x => x.Email == userModel.Email
                 && x.Password == userPassword).FirstOrDefault();
                var Data = db.Users.Where(x => x.Email == userModel.Email
                 && x.Password == userPassword).FirstOrDefault();

                if (userData == null)
                {
                    userModel.LoginErrorMessage = "Wrong Email or Password";
                    return View("Index", userModel);
                }
                else if (Data.IsEmailVerified == false)
                {
                    userModel.LoginErrorMessage = "Your email must be verified before you can log in. A new verification link has been sent to your email ";
                    SendVerificationLinkEmail(userData.Email, userData.ActivationCode.ToString());
                    return View("Index", userModel);
                }
                else
                {
                    if (userData.Type)
                    {
                        Session["Admin"] = true;
                    }
                    else
                    {
                        Session["Admin"] = false;
                    }

                    Session["User_id"] = userData.User_id;
                    Session["Name"] = userData.Name;
                    
                    return RedirectToAction("Index", "Home");
                }
            }
        }
        [NonAction]
        public void SendVerificationLinkEmail(string email, string activationCode, string emailFor = "VerifyAccount")
        {
            var verifyUrl = "/Register/" + emailFor + "/" + activationCode;
            var link = Request.Url.AbsoluteUri.Replace(Request.Url.PathAndQuery, verifyUrl);

            var fromEmail = new MailAddress("bookus094@gmail.com", "BookStore");
            var toEmail = new MailAddress(email);
            var fromEmailPassword = "Hogeschool_rotterdam1";

            string subject = "";
            string body = "";
            if (emailFor == "VerifyAccount")
            {
                subject = "Your account is successfully created";

                body = "<br/><br/> Welcome by BooksR'us your account has been" +
                   " successfuly created. Please click on the link below to verify your account" +
                   " <br/><br/><a herf='" + link + "'>" + link + "</a> ";
            }

            else if (emailFor == "ResetPassword")
            {
                subject = "Reset Password";
                body = "Hallo,<br/><br/>Dear User of BooksR'us, we have received a request to reset your password. If you really want to reset your password, you can click on the link below" +
                       "<br/><br/><a herf='" + link + "'>" + link + "</a>";
            }
            var smtp = new SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
            };

            using (var message = new MailMessage(fromEmail, toEmail)
            {
                Subject = subject,
                Body = body,
                IsBodyHtml = true
            })
                smtp.Send(message);
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult ForgotPassword()
        {
            return View();
        }

        public ActionResult LogOut()
        {
            Session["Admin"] = null;
            Session["User_id"] = null;
            Session["ReviewInput"] = null;
            return RedirectToAction("Index", "Home");
        }
    }
}

webtest/webtest/webtest/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using webtest.Models;
using PagedList;
using PagedList.Mvc;

namespace webtest.Controllers
{
    public class ProductController : Controller
    {
        //Connectie met database
        DatabaseEntities1 db = new DatabaseEntities1();
        List<string> cart = new List<string>();
        // GET: Product
        public ActionResult Index(double? favo, string url, double? cart, double? del, double isbn = 0, string date = "", bool addreview = false, int readMore = 0, bool delete = false, bool plus = false, bool min = false, decimal rating = 0, string review = "", string name = "", string surname = "", bool deleteReview = false, int deleteId = 0, bool urlBool = false)
        {
            if (urlBool == true)
            {
                Session["URL"] = url;
            }
            string favoISBN = favo.ToString();
            string cartISBN = cart.ToString();
            var _isbn = isbn.ToString();
            Dictionary<Book, int> cartQuantity = new Dictionary<Book, int>();
            int User_id = 0;

            if (favoISBN != "" && favoISBN != null)
            {
                FavoriteList(_isbn);
            }

            //Cart button toevoegen
            if (cartISBN != "" && cartISBN != null)
            {
                if (Session["User_id"] != null)
                {
                    var list = db.Carts.Select(s => s);

                    int user_id = Convert.ToInt32(Session["User_id"]);

                    bool has = list.Any(cus => cus.ISBN == cart && cus.User_id == user_id);

                    if (has && plus != true)
                    {
                        using (DatabaseEntities1 db = new DatabaseEntities1())
                        {
                            db.Carts.Remove(db.Carts.Single(cus => cus.ISBN == cart && cus.User_id == user_id));
                            db.SaveChanges();
                        }

                    }
                    else if (plus != true)
                    {
                        using (DatabaseEntities1 db = new DatabaseEntities1())
                        {
                            var cartObj = new Cart() { User_id = user_id, ISBN = Convert.ToDouble(cart), Quantity = 1 };
                            db.Carts.Add(cartObj);
                            db.SaveChanges();
                        }
                    }
                }
                else
                {
                    // UNREGISTERED USER
                    if (Session["shoppingCart"] == null || Session["shoppingCart"] == "")
                    {
                        Session["shoppingCart"] = cartISBN;
                        plus = false;
                    }
                    else if (plus == false)
                    {
                        List<string> isbns = Session["shoppingCart"].ToString().Split(',').ToList();
                        //Check of die al in je cart zit.
                        if (isbns.Contains(cartISBN))
                        {

                            isbns.Remove(cartISBN);
                            var newcart = String.Join(",", isbns);
                            Session["shoppingCart"] = newcart;

                        }
                        else
                        {
                            Session["shoppingCart"] = Session["shoppingCart"] + "," + cartISBN;
                        }
                    }
                }
            }

            decimal totalPrice = 0;
            string deleteISBN = del.ToString();

            List<Book> bookList = new List<Book>();
            List<Book> bookReturn = new List<Book>();

            if (Session["User_id"] != null)
            {
                User_id = Convert.ToInt32(Session["User_id"]);

                // Session voor de input fields
                Review(_isbn);


                //Verwijder item voor geregistreerde user
                if (deleteISBN != "" && deleteISBN != null)
                {
                    using (DatabaseEntities1 db = new DatabaseEntities1())
                    {
                        db.Carts.Remove(db.Carts.Single(x => x.ISBN == del));
                        db.SaveChanges();
                    }
                }

                if (plus)
                {
                    double isbnD = Convert.ToDouble(isbn);
                    var book = db.Carts.Where(x => x.ISBN == isbnD).FirstOrDefault();
                    if (book == null)
                    {
                        var cartObj = new Cart() { User_id = User_id, ISBN = Convert.ToDouble(cart), Quantity = 1 };
                        db.Carts.Add(cartObj);
                    }
                    else
                    {
                        book.Quantity += 1;
                    }
                    db.SaveChanges();
                }

                if (min)
                {
                    double isbnD = Convert.ToDouble(isbn);
                    var book = db.Carts.Where(x => x.ISBN == isbnD).FirstOrDefault();
                    if (book.Quantity == 1)
                    {
                        using (DatabaseEntities1 db = new DatabaseEntities1())
                        {
                            db.Carts.Remove(db.Carts.Single(x => x.ISBN == isbnD));
                            db.SaveChanges();
                        }
                    }
                    else
                    {
                        book.Quantity -= 1;
                    }

                    db.SaveChanges();
                }
            }

            else
            {

                if (Session["shoppingCart"] != null)
                {
                    List<string> isbns = Session["shoppingCart"].ToString().Split(',').ToList();
                    var bookListQ = from x in isbns
                                    group x by x into g
                                    let count = g.Count()

                                    select new { Value = g.Key, Count = count };

                    //Deletes product from cart
                    if (isbns.Contains(_isbn) && delete)
                    {
                        isbns.RemoveAll(s => _isbn == s);
                        var newcart = String.Join(",", isbns);
                        Session["shoppingCart"] = newcart;
                        delete = false;
                    }

                    if (plus)
                    {
                        isbns.Add(_isbn);
                        var newcart = String.Join(",", isbns);
                        Session["shoppingCart"] = newcart;

                        plus = false;
                    }

                    if (min)
                    {
                        isbns.Remove(_isbn);
                        var newcart = String.Join(",", isbns);
                        Session["shoppingCart"] = newcart;

                        min = false;
                    }
                    try
                    {

                        foreach (var book in bookListQ)
                        {
                            int count = Convert.ToInt32(book.Count);

                            var bookAmount = count;
                            ViewData[book.Value] = bookAmount;
                        }

                        ViewBag.totalPrice = totalPrice;
                    }
                    catch (FormatException)
                    {

                    }
                }
            }

            // Adds the review to the review table in the database
            if (addreview)
            {
                DateTime _date = Convert.ToDateTime(date);
                int _user_id = Convert.ToInt32(Session["User_id"]);

                var maxId = db.Reviews.Max(m => m.Id);

                var newReview = new Review()
                {
                    Id = maxId + 1,
                    Name = name,
                    Surname = surname,
                    Rating = rating,
                    Date = _date,
                    Review1 = review,
                    ISBN = isbn,
                    User_id = _user_id

                };

                db.Reviews.Add(newReview);
                db.SaveChanges();

                // Hides the input fields in the view
                Session["ReviewInput"] = null;

                decimal averageRating = (from r in db.Reviews
                                         where r.ISBN == isbn
                                         select r.Rating).Average();

                var BooksTable = (from b in db.Books
                                  where b.ISBN == isbn
                                  select b).ToList();

                foreach (var x in BooksTable)
                {
                    x.Rating = averageRating;
                }

                db.SaveChanges();
            }

            // Admin can delete reviews on the product page
            if (deleteReview)
            {
                using (DatabaseEntities1 db = new DatabaseEntities1())
                {
                    db.Reviews.Remove(db.Reviews.Single(x => x.Id == deleteId));
                    db.SaveChanges();

                    var BooksTable = (from b in db.Books
                                      where b.ISBN == isbn
                                      select b).ToList();

                    try
                    {
                        Decimal averageRating = (from r in db.Reviews
                                                 where r.ISBN == isbn
                                                 select r.Rating).Average();

                        foreach (var x in BooksTable)
                        {
                            x.Rating = averageRating;
                        }

                        db.SaveChanges();
                    }
                    catch
                    {

webtest/webtest/webtest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", false)
</body>
</html>

webtest/webtest/webtest/Views/Shared/_customLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/Main.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css'>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.bundle.js"></script>
    <title>Chart.js Chart</title>
</head>
<body>

    <header>
        <div class="container">

            <a class="logo" href="@Url.Action("Index", "Home")">Books'<span>R'Us</span></a>

            <nav class="site-nav">
                <ul>
                    @{
                        <li><a href="@Url.Action("ShoppingCart", "Home")"><i class="fa fa-shopping-cart site-nav--icon"></i> Cart</a></li>
                        if (Session["User_id"] != null)
                        {
                            <li><a href="@Url.Action("OrderHistory", "OrderHistory")"><i class="fa fa-eye site-nav--icon"></i>Order History</a></li>
                            <li><a href="@Url.Action("Index", "Favorites")"><i class="fa fa-heart site-nav--icon"></i>Favorites</a></li>
                            if (Session["Admin"] != null)
                            {
                                bool admin = Convert.ToBoolean(Session["Admin"]);
                                if (admin)
                                {
                                    <li><a href="@Url.Action("ProductList", "Admin")"><i class="fa fa-shield site-nav--icon"></i>Admin</a></li>
                                }
                            }
                            <li><a href="@Url.Action("Logout", "Login")"><i class="fa fa-user site-nav--icon"></i>Logout</a></li>

                        }

                        else
                        {
                            <li><a href="@Url.Action("Index", "Login")"><i class="fa fa-user site-nav--icon"></i>Login</a></li>
                        }




                    }

                </ul>
            </nav>
            <div class="menu-toggle">
                <div class="hamburger"></div>
            </div>

        </div>
    </header>

    <nav class="nav2">
        <ul>
            <div class="wrap">
                <div class="search">
                    <!-- GET request aan de Results View van de Product controller.-->
                    <!-- Data in de zoekbar wordt meegegeven aan de Results Action in de Products Controller-->
                    @using (Html.BeginForm("Results", "Product", FormMethod.Get))
                    {
                        <input type="text" name="MinPrice" , value="@Request.QueryString["MinPrice"]" style="display:none">
                        <input type="text" name="MaxPrice" , value="@Request.QueryString["MaxPrice"]" style="display:none">
                        <input type="text" name="Order" , value="@Request.QueryString["Order"]" style="display:none">
                        <input type="text" name="Rating" , style="display:none" value="@Request.QueryString["Rating"]">
                        <input type="text" name="Category" , style="display:none" value="@Request.QueryString["Category"]">
                        <div id="searchBar">
                        @Html.TextBox("Search")
                        <button type="submit" class="searchButton">
                            <i class="fa fa-search"></i>
                        </button>
                        </div>
                    }
                </div>
            </div>
        </ul>
    </nav>
    <div class="nav3">
        <a href="@Url.Action("Results", "Product", new {Category = "Fiction"}, null)">Fiction</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Biography"}, null)">Biography</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Sports"}, null)">Sports</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Art & Photography"}, null)">Art & Photography</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Science & Nature"}, null)">Science & Nature</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Business"}, null)">Business</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Education"}, null)">Education</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Food & Drink"}, null)">Food & Drink</a>
        <a href="@Url.Action("Results", "Product", new {Category = "Style & Beauty"}, null)">Style & Beauty</a>

        <div class="dropdown">
            <button class="dropbtn">
                Categories
                <i class="fa fa-caret-down"></i>
            </button>
            <div class="dropdown-content">

                @Html.ActionLink(
                     "Diet & Fitness",                                                  // linkText
                     "Results",                                    // actionName
                     "Product",                                                   // controllerName
                     new {                                                     // routeValues
                         Category = "Diet & Fitness"
                     },
                     null                                                      // htmlAttributes
                )

                @Html.ActionLink(
                    "History & Politics",                                                  // linkText
                    "Results",                                    // actionName
                    "Product",                                                   // controllerName
                    new {                                                     // routeValues
                        Category = "History & Politics"
                    },
                    null                                                      // htmlAttributes
               )

                @Html.ActionLink(
                     "Home & Garden",                                                  // linkText
                     "Results",                                    // actionName
                     "Product",                                                   // controllerName
                     new {                                                     // routeValues
                         Category = "Home & Garden"
                     },
                     null                                                      // htmlAttributes
                )

                @Html.ActionLink(
                     "Mind Body Spirit",                                                  // linkText
                     "Results",                                    // actionName
                     "Product",                                                   // controllerName
                     new {                                                     // routeValues
                         Category = "Mind Body Spirit"
                     },
                     null                                                      // htmlAttributes
                )

                @Html.ActionLink(
                     "Parenting",                                                  // linkText
                     "Results",                                    // actionName
                     "Product",                                                   // controllerName
                     new {                                                     // routeValues
                         Category = "Parenting"
                     },
                     null                                                      // htmlAttributes
                )
            </div>
        </div>
    </div>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.min.js'></script>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js'></script>

    <script src="~/Scripts/Test.js"></script>

    <div>
        @RenderBody()
    </div>
</body>
</html>